### ISSUE TITLE
Several Japanese titles use English box art.

### ISSUE THREAD

**Issue by Murray1Kim** [codewario/PocketLibraryImages#19]
**Release version of the sample image pack**
[v1.2]

I checked 55 Japanese titles and found that several of them used box art from the European and American versions.
Can you fix this?

- Super Mario Advance 4 - Super Mario 3 + Mario Brothers (Japan) (Rev 2).png
Must be the same as [Super Mario Advance 4 - Super Mario 3 + Mario Brothers (Japan) (Rev 1).png]

- Dragon Ball Z - Bukuu Tougeki (Japan).png
No Japanese box art

- Dragon Ball - Advance Adventure (Korea).png
Must be the same as [Dragon Ball - Advance Adventure (Japan).png]

- Final Fantasy I, II Advance (Japan) (Rev 1).png
Must be the same as [Final Fantasy I, II Advance (Japan) (Rev 1) (Virtual Console).png]

- Final Fantasy VI Advance (Japan).png
Must be the same as [Final Fantasy VI Advance (Japan) (Virtual Console).png]

- Frontier Stories (Japan).png
No Japanese box art

- Riviera - Yakusoku no Chi Riviera (Japan).png
Must be the same as [Riviera - Yakusoku no Chi Riviera (Japan) (Rev 1).png]

- Shin Sangoku Musou Advance (Japan).png
Must be the same as [Shin Sangoku Musou Advance (Japan) (Rev 1).png]

- Super Mario Advance 3 - Yoshi's Island + Mario Brothers (Japan).png
Must be the same as [Super Mario Advance 3 - Yoshi's Island + Mario Brothers (Japan) (Virtual Console).png]

- Super Mario Advance 4 - Super Mario 3 + Mario Brothers (Japan) (Rev 1).png
- Super Mario Advance 4 - Super Mario 3 + Mario Brothers (Japan) (Rev 2).png
Must be the same as [Super Mario Advance 4 - Super Mario 3 + Mario Brothers (Japan).png]

- Super Mario Advance - Super Mario USA + Mario Brothers (Japan).png
Must be the same as [Super Mario Advance - Super Mario USA + Mario Brothers (Japan) (Virtual Console).png]

**Comment by codewario** [comment]
I'll take a look at this in the coming weeks and see if it's either a filtering issue or if I need to hard map those titles to specific images.

Did you confirm that the correct images for those revisions exist in the GBA libretro-thumbnails repo? If the images for those revisions don't actually exist, and instead point to another revision's art from another region, there's not much I'll be able to do on this side of things.

**Comment by codewario** [comment]
Spot checking some of these, the box art exists but is incorrect for those revisions of the games, so I can't fix those unless there are correct regional boxarts to redirect to in that repo. While I can remap specific titles to alternative titles instead (useful when libretro-thumbnails uses a name incompatible with the corresponding no-intro title entry), remapping in this way when the image is incorrect could result in the correct images getting missed for other types.

In other words, for some of these, the correct artwork exists for some image types but not others (e.g. the boxart is for the incorrect region but the title art is for the correct region when comparing artworks for the same title). While it's possible to implement art-specific remapping, this was already a painstaking process to implement for all incorrectly mapped titles and I'm not sure that going through this again for each art type is worth the trouble.

If you can confirm that any of the box artwork for the games listed above are also incorrect for the corresponding title screen and snapshot images, I can remap that title. Otherwise, the best way to fix this is to fix the problem at the source and provide the correct images to libretro-thumbnails.

**Comment by Murray1Kim** [comment]
I understand what you said.
I am using a conversion tool to replace some files for personal use.
I will later request libretro-thumbnails to replace the incorrect image.

thank you for your hard work.
